# Generated by Django 5.2.4 on 2025-07-27 13:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prodmast",
            options={
                "ordering": ["prod_name"],
                "verbose_name": "Product Master",
                "verbose_name_plural": "Product Masters",
            },
        ),
        migrations.AlterModelOptions(
            name="stockdetail",
            options={
                "verbose_name": "Stock Detail",
                "verbose_name_plural": "Stock Details",
            },
        ),
        migrations.AlterModelOptions(
            name="stocktrans",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Stock Transaction",
                "verbose_name_plural": "Stock Transactions",
            },
        ),
        migrations.AddField(
            model_name="prodmast",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prodmast",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Set to false to deactivate product"
            ),
        ),
        migrations.AddField(
            model_name="prodmast",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="stockdetail",
            name="notes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="stockdetail",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Price cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="stocktrans",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocktrans",
            name="created_by",
            field=models.CharField(
                blank=True, help_text="Who created this transaction", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="stocktrans",
            name="notes",
            field=models.TextField(blank=True, help_text="Optional transaction notes"),
        ),
        migrations.AlterField(
            model_name="prodmast",
            name="prod_desc",
            field=models.TextField(
                blank=True, help_text="Optional product description"
            ),
        ),
        migrations.AlterField(
            model_name="prodmast",
            name="prod_name",
            field=models.CharField(
                help_text="Product name must be unique", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="stockdetail",
            name="quantity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Quantity must be at least 1"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="stocktrans",
            name="transaction_type",
            field=models.CharField(
                choices=[("IN", "Stock In"), ("OUT", "Stock Out")],
                help_text="Select transaction type",
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockdetail",
            unique_together={("product", "transaction")},
        ),
    ]
